### PR TITLE
Allow numbers

### PR DESCRIPTION
**Pull request by ambroiseRabier**
I have added the possibility to put number, for array, in the path. I have make this work on another project. I tried to `npm run build` on this project but failed with a strange issue `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed`. I guess I leave it to you to recompile the project :) . Nice package you've made.

### CODE REVIEW

**Comment by ambroiseRabier** [comment]
Edit: I have added a way of making test, and resolved an issue with pathOf was removing `0` indexes. The filter function was not using triple equals operator. Thus confusing `0` with `undefined`.
I also fixed `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed`, by commenting a bottom part of the code, it did not seem to break anything, was it WIP code never compiled, or how is that you did not had that issue?

**Comment by Morglod** [comment]
@ambroiseRabier there is a bug with non constant array types
image

In arrays like this `x[]` may be any index, even if it is `[]` in real.  
User should define arrays as `[ x ] as const` for properly type checking.

Added typeguard for this
```ts
type FixedArrayCap = 0|1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19;

type _POD_ = string|number|boolean|symbol|undefined|null|((...args: any) => any);

type Arr<T> = (
    (T[] & { length: FixedArrayCap }) |
    (readonly T[] & { length: FixedArrayCap })
);

export type PodJSON =
    _POD_|
    Arr<_POD_>|
    { [x in string]: PodJSON }|
    { [x in string]: Arr<PodJSON> };
```

Now there will be type error if array is not const defined:
image
image

@ambroiseRabier can you please review https://github.com/Morglod/ts-pathof/pull/4

**Comment by ambroiseRabier** [comment]
If I understand it right, only valid indexes are allowed to be used.
In case of

```ts
const d = {x: [{b: 123}] as const};
```

then,
```ts
pathOf(d, 'x', 0, 'b');
```
is valid.

But 

```ts
pathOf(d, 'x', 51, 'b');
```
is invalid.

---

Have I understood it right ?

**Comment by Morglod** [comment]
@ambroiseRabier Yes

**Comment by ambroiseRabier** [comment]
What happen when the array is not a constant ? Is any index valid ?

**Comment by Morglod** [comment]
Will be type error if array is not a constant  
Ye may be it's a problem for some cases

**Pull request merged**
